### ISSUE TITLE
Permission 'storage.buckets.get' denied on "apache-beam-ml" bucket

### ISSUE THREAD

**Issue by tasuku-ito** [google/dataflow-ml-starter#23]
DirectRunner executed with "make run-direct" fails to run because public users do not have storage.buckets.get permission to the apache-beam-ml bucket.

Since DirectRunner uses model files and datasets stored in apache-beam-ml bucket as input, it seems that permission 'storage.buckets.get' to this bucket is necessary.

I work around this problem by copying the data to a bucket I have created in my project.

**Comment by liferoad** [comment]
This should be fixed with Beam 2.55.0 (https://github.com/apache/beam/pull/30205)
